// <auto-generated />
using System;
using Docket.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Docket.Infrastructure.Migrations
{
    [DbContext(typeof(DocketDbContext))]
    [Migration("20260224225538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Docket.Domain.Entities.ActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AssignedInAbsentia")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceActionItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ResponsibleId");

                    b.HasIndex("SourceActionItemId");

                    b.HasIndex("Status");

                    b.HasIndex("TopicId");

                    b.ToTable("ActionItems");
                });

            modelBuilder.Entity("Docket.Domain.Entities.ActionItemLabel", b =>
                {
                    b.Property<Guid>("ActionItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("TEXT");

                    b.HasKey("ActionItemId", "LabelId");

                    b.HasIndex("LabelId");

                    b.ToTable("ActionItemLabels");
                });

            modelBuilder.Entity("Docket.Domain.Entities.ActionItemNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActionItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ActionItemId", "CreatedAt");

                    b.ToTable("ActionItemNotes");
                });

            modelBuilder.Entity("Docket.Domain.Entities.InfoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PinnedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TopicId");

                    b.ToTable("InfoItems");
                });

            modelBuilder.Entity("Docket.Domain.Entities.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Labels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Category = "Action",
                            Color = "#1565C0",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystem = true,
                            Name = "Decision"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Category = "Action",
                            Color = "#6A1B9A",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystem = true,
                            Name = "Proposal"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Category = "Action",
                            Color = "#37474F",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystem = true,
                            Name = "New"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Category = "Status",
                            Color = "#2E7D32",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystem = true,
                            Name = "Status:GREEN"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Category = "Status",
                            Color = "#F57F17",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystem = true,
                            Name = "Status:YELLOW"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Category = "Status",
                            Color = "#B71C1C",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystem = true,
                            Name = "Status:RED"
                        });
                });

            modelBuilder.Entity("Docket.Domain.Entities.MeetingSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalCalendarId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("MeetingSeries");
                });

            modelBuilder.Entity("Docket.Domain.Entities.Minutes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AbandonedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AbandonedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("AbandonmentNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FinalizedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalNote")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GlobalNotePinned")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PreviousMinutesId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AbandonedBy");

                    b.HasIndex("FinalizedBy");

                    b.HasIndex("PreviousMinutesId");

                    b.HasIndex("ScheduledFor");

                    b.HasIndex("SeriesId");

                    b.ToTable("Minutes");
                });

            modelBuilder.Entity("Docket.Domain.Entities.MinutesAttendee", b =>
                {
                    b.Property<Guid>("MinutesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("MinutesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MinutesAttendees");
                });

            modelBuilder.Entity("Docket.Domain.Entities.SeriesParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SeriesId", "UserId")
                        .IsUnique();

                    b.ToTable("SeriesParticipants");
                });

            modelBuilder.Entity("Docket.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MinutesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResponsibleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceTopicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MinutesId");

                    b.HasIndex("ResponsibleId");

                    b.HasIndex("SourceTopicId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Docket.Domain.Entities.TopicLabel", b =>
                {
                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("TEXT");

                    b.HasKey("TopicId", "LabelId");

                    b.HasIndex("LabelId");

                    b.ToTable("TopicLabels");
                });

            modelBuilder.Entity("Docket.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Docket.Domain.Entities.ActionItem", b =>
                {
                    b.HasOne("Docket.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Docket.Domain.Entities.User", "Responsible")
                        .WithMany("OwnedActionItems")
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Docket.Domain.Entities.ActionItem", "SourceActionItem")
                        .WithMany()
                        .HasForeignKey("SourceActionItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Docket.Domain.Entities.Topic", "Topic")
                        .WithMany("ActionItems")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Responsible");

                    b.Navigation("SourceActionItem");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Docket.Domain.Entities.ActionItemLabel", b =>
                {
                    b.HasOne("Docket.Domain.Entities.ActionItem", "ActionItem")
                        .WithMany("ActionItemLabels")
                        .HasForeignKey("ActionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Docket.Domain.Entities.Label", "Label")
                        .WithMany("ActionItemLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionItem");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("Docket.Domain.Entities.ActionItemNote", b =>
                {
                    b.HasOne("Docket.Domain.Entities.ActionItem", "ActionItem")
                        .WithMany("Notes")
                        .HasForeignKey("ActionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Docket.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActionItem");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Docket.Domain.Entities.InfoItem", b =>
                {
                    b.HasOne("Docket.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Docket.Domain.Entities.Topic", "Topic")
                        .WithMany("InfoItems")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Docket.Domain.Entities.MeetingSeries", b =>
                {
                    b.HasOne("Docket.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Docket.Domain.Entities.Minutes", b =>
                {
                    b.HasOne("Docket.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AbandonedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Docket.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("FinalizedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Docket.Domain.Entities.Minutes", "PreviousMinutes")
                        .WithMany()
                        .HasForeignKey("PreviousMinutesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Docket.Domain.Entities.MeetingSeries", "Series")
                        .WithMany("Minutes")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreviousMinutes");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Docket.Domain.Entities.MinutesAttendee", b =>
                {
                    b.HasOne("Docket.Domain.Entities.Minutes", "Minutes")
                        .WithMany("Attendees")
                        .HasForeignKey("MinutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Docket.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Minutes");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Docket.Domain.Entities.SeriesParticipant", b =>
                {
                    b.HasOne("Docket.Domain.Entities.MeetingSeries", "Series")
                        .WithMany("Participants")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Docket.Domain.Entities.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Docket.Domain.Entities.Topic", b =>
                {
                    b.HasOne("Docket.Domain.Entities.Minutes", "Minutes")
                        .WithMany("Topics")
                        .HasForeignKey("MinutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Docket.Domain.Entities.User", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Docket.Domain.Entities.Topic", "SourceTopic")
                        .WithMany()
                        .HasForeignKey("SourceTopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Minutes");

                    b.Navigation("Responsible");

                    b.Navigation("SourceTopic");
                });

            modelBuilder.Entity("Docket.Domain.Entities.TopicLabel", b =>
                {
                    b.HasOne("Docket.Domain.Entities.Label", "Label")
                        .WithMany("TopicLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Docket.Domain.Entities.Topic", "Topic")
                        .WithMany("TopicLabels")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Docket.Domain.Entities.ActionItem", b =>
                {
                    b.Navigation("ActionItemLabels");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Docket.Domain.Entities.Label", b =>
                {
                    b.Navigation("ActionItemLabels");

                    b.Navigation("TopicLabels");
                });

            modelBuilder.Entity("Docket.Domain.Entities.MeetingSeries", b =>
                {
                    b.Navigation("Minutes");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Docket.Domain.Entities.Minutes", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Docket.Domain.Entities.Topic", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("InfoItems");

                    b.Navigation("TopicLabels");
                });

            modelBuilder.Entity("Docket.Domain.Entities.User", b =>
                {
                    b.Navigation("OwnedActionItems");

                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
